---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

baseURL: https://scholarsproject.netlify.app/
title: ""
theme: inventory
languageCode: ro-ro
defaultContentLanguage: ro
enableEmoji: true
enableGitInfo: true

# Optional: Add Google Analytics tracking support.
googleAnalytics: ""


# --- security settings ---

security:
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']


# --- markup settings ---

markup:
  asciidocExt:
    preserveTOC: true
    sectionNumbers: true
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: murphy
    tabWidth: 4


# --- privacy settings ---

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true

# --- blogdown suggests ---

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$


# --- custom settings ---

params:
  # "Edit this page" feature: git forge content base link
  # [Example] editPrefix: https://github.com/username/repo-name/blob/main/content
  editPrefix: https://github.com/unicef/inventory-hugo-theme/blob/main/exampleSite/content

  # Shown on all pages. When logo is empty, it will show your site title, set above.
  logo: images/324good3_v2_sizetiny.png
  # empty is: ""

  # OpenGraph data
  description: UNICEF Inventory Theme. This Hugo-powered static site is documentation for and an example of the UNICEF Inventory Theme.
  author: UNICEF Office of Innovation, and others
  # Tip: Find a royalty-free image from unsplash.com for an OpenGraph image.
  image: "images/banner.jpg"

  # customize color
  primary_color: "#1CABE2"
  primary_color_light: "#1b66b1"
  body_color: "#f2f4f6"
  text_color: "#636363"
  text_color_dark: "#374ea2"
  text_title_color: "#ffffff"
  white_color: "#ffffff"
  light_color: "#f8f9fa"

  # font family (choose from https://fonts.google.com/)
  font_family: "Lato"

  # contact form action (works with https://formspree.io)
  contact_form_action: "#"

  # related article number limit
  article_count: 3

  # brand and identity information
  brand:
    parent_org_name: UNIBUC
    parent_org_url: https://unibuc.ro/
    parent_org_url_legal: https://unibuc.ro/privacy-policy/?lang=en
  footer:
    mainSite: https://www.unicef.org/innovation/
    mainSiteName: UNICEF Office of Innovation


# --- social platform settings ---
# themify icon pack : https://themify.me/themify-icons

  social:
    - icon: ti-email
      name: Scholars e-mail address
      link: mailto:scholars@fpse.unibuc.ro
    - icon: ti-facebook
      name: Scholars facebook page
      link: https://facebook.com/
    - icon: ti-github
      name: UNICEF Inventory Theme on GitHub
      link: https://github.com/scholarsproject/scholarsproject_website
    # - icon: ti-twitter-alt
    #   name: "@UNICEFinnovate on Twitter"
    #   link: https://twitter.com/UNICEFinnovate


# --- taxonomy settings ---

taxonomies:
  alert: alerts
  category: categories
  downloadable: downloadBtn


# --- multilingual settings ---

Languages:
############################# English #############################
  en:
    languageName: en
    languageCode: en-us
    weight: 1
    home: Home
    copyright: "Copyright &copy; 2021-2025 SCOLARS Team <br> Website created using theme by [UNICEF Office of Innovation](https://www.unicef.org/innovation/) for [Hugo](https://gohugo.io/)"
    params:
      banner:
        title: Welcome to Scholars Project
        subtitle: Social Contribution through Health Optimization Literacy to Academic Resilience in Schools
        bg_image: images/banner.jpg
        placeholder: Have a question? Search the site here or read the FAQ.
      cta:
        enable: true
        title: Participate to a study
        content: Let us know if you want to take part in one of our studies by clicking the button below and sharing some information about yourself.
        button:
          enable: true
          label: I'd like to participate
          link: contact
      footer:
        description: The SCHOLARS reasearch grant was awarded through the [PN-III-ID-PCE-2021-3](https://uefiscdi.gov.ro/proiecte-de-cercetare-exploratorie) program of [uefiscdi](https://uefiscdi.gov.ro/), financing contract PN-III-P4-PCE-2021-1528.

    # --- navigation menu ---
    menu:
      main:
        - name: About us
          weight: 10
          url: about
        - name: FAQ
          weight: 20
          url: faq

        - name: studies
          weight: 40
          url: studies
          hasChildren: true
        # Sub-pages in this drop-down should correspond to categories created in /content/
        - name: 1. Proposal
          parent: studies
          weight: 10
          url: proposal
        - name: 2. Participation
          parent: studies
          weight: 20
          url: participation
        - name: 3. Results
          parent: studies
          weight: 30
          url: results
        - name: 4. Contributions
          parent: studies
          weight: 50
          url: contributions

        - name: Contact
          weight: 50
          url: contact
############################# español / Spanish #############################
  ro:
    languageName: ro
    languageCode: ro-ro
    weight: 2
    home: Acasă
    copyright: "Drepturi de autor &copy; 2021-2025 Echipa SCOLARS <br> Website creat cu șablonul [UNICEF Office of Innovation](https://www.unicef.org/innovation/) pentru [Hugo](https://gohugo.io/)"
    params:
      banner:
        title: Bun venit pe Proiectul Scholars
        subtitle: Contribuție Socială prin Optimizarea Literației în Sănătate Mentală pentru Reziliență Academică în Școli
        bg_image: images/banner.jpg
        placeholder: Aveți o întrebare? Căutați aici sau citiți FAQ.
      cta:
        enable: true
        title: Participați la un studiu
        content: Semnalați-ne dorința dvs. de a lua parte la unul dintre studiile noastre apasând butonul de mai jos și împărtășind câteve informații despre dvs.
        button:
          enable: true
          label: Vreau să particip
          link: contact
      footer:
        description: Grantul SCHOLARS a fost câștigat prin competiție publică în cadrul programului [PN-III-ID-PCE-2021-3](https://uefiscdi.gov.ro/proiecte-de-cercetare-exploratorie) oferit de [uefiscdi](https://uefiscdi.gov.ro/), contract de finanțare PN-III-P4-PCE-2021-1528.

    # --- navigation menu ---
    # --- navigation menu ---
    menu:
      main:
        - name: Despre noi
          weight: 10
          url: about
        - name: FAQ
          weight: 20
          url: faq

        - name: studii
          weight: 40
          url: studies
          hasChildren: true
        # Sub-pages in this drop-down should correspond to categories created in /content/
        - name: 1. Prezentare
          parent: studii
          weight: 10
          url: proposal
        - name: 2. Participare
          parent: studii
          weight: 20
          url: participation
        - name: 3. Rezultate
          parent: studii
          weight: 30
          url: results
        - name: 4. Contribuții
          parent: studii
          weight: 50
          url: contributions

        - name: Contact
          weight: 50
          url: contact

